import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import SideBar from './components/SideBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body>
        
       
      <main className='flex bg-[#212121]'>
        <div className='basis-[15%]'>
        <SideBar/> 

        </div>
      <section className='basis-[85%]'>
      <Nav/>
      <div className={inter.className}>{children}</div>
      </section>
      </main>
      
      
      </body>
     
    </html>
  )
}
