import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import SideBar from './components/SideBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body>
        
       
      <main className='flex justify-between bg-[#212121] max-w-[1500px] mx-auto '>
        <div className='w-[232px] '>
        <SideBar/> 

        </div>
      <section className='w-[calc(100%-232px)]'>
      <Nav/>
      <div className={inter.className}>{children}</div>
      </section>
      </main>
      
      
      </body>
     
    </html>
  )
}
